name: Quick Check

on:
  push:
    branches: [main, master]
    paths:
      - 'README.md'
      - 'docs/**'
      - '.github/**'
      - '!.github/workflows/**'

jobs:
  lint-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Cache node_modules
        uses: actions/cache@v4
        id: node-modules-cache
        with:
          path: |
            node_modules
            ~/.npm
          key: ${{ runner.os }}-node-20-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-20-
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci
        if: steps.node-modules-cache.outputs.cache-hit != 'true'

      - name: Install dependencies (cache hit)
        run: npm ci
        if: steps.node-modules-cache.outputs.cache-hit == 'true'

      - name: Check code formatting
        run: npm run format:check

      - name: Run linter
        run: npm run lint
